# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wlapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='visited_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
